### ISSUE TITLE
What is the status of iOS Bluetooth?

### ISSUE THREAD

**Issue by kawa89** [themobilecoder/headset_connection_event#1]
Hello, I wanted to know, what is the status of iOS and Bluetooth headsets? Is it in progress or impossible to do?

**Comment by rafdls** [comment]
> Hello, I wanted to know, what is the status of iOS and Bluetooth headsets? Is it in progress or impossible to do?

Hey. I apologise but I'm currently not active with this project at the moment.

I think the way I used this library is that if the bluetooth headset gets disconnected from the phone, the media player should stop. The way iOS works is that it automatically stops/pauses the media that is currently playing when bluetooth gets disconnected. In Android, we need to use this library.

Because of that, I didn't really had the need to listen to bluetooth events. There might be a way to listen to these events, but I'm not really aware.

**Comment by kawa89** [comment]
Thanks for a quick response. I need to check if a headset is connected, before playing the sound. It's a mandatory step before going to the next screen in the app. So I will probably have to develop something else then.

**Comment by schisms** [comment]
Opened pull request to add this feature https://github.com/themobilecoder/headset_connection_event/pull/4

Appears to work fine but please test

**Comment by rafdls** [comment]
@schisms Thank you so much for the PR!

**Comment by rafdls** [comment]
@schisms Tested it with an iphone using the example app and it works!


Thanks again and will publish this soon. @kawa89, will close this as @schisms added this feature.

**Comment by kawa89** [comment]
Nice ;)
@themobilecoder To be honest I already did that on my forked repo ;-)
I also additionally added support for checking if a wired or wireless headset is connected and probably improved some logic.
All the commits you can check here: https://github.com/kawa89/headset_connection_event/commits/master
If you think it will improve your library, I can make a PR :)

**Comment by rafdls** [comment]
@kawa89 That's awesome mate. Feel free to make a PR if you like.
